#!/usr/bin/env bash

set -euo pipefail

log() {
  printf '==> %s\n' "$*"
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: ./draw-keymap.sh [options] [variant]

Generate staged keymap-drawer visualizations for a ZMK keymap in this repo.

Arguments:
  variant              Config stem under config/, default: toucan

Options:
  --skip-install       Fail instead of installing keymap-drawer when missing
  -h, --help           Show this help text

Environment overrides:
  PYTHON_BIN             Python interpreter used to create the virtualenv
  VENV_DIR               Virtualenv directory for keymap-drawer
  DRAW_ROOT              Output directory for generated artifacts
  DRAW_CONFIG            keymap-drawer config file
  PREPARE_SCRIPT         YAML post-processor that builds base/keymap inputs
  LEADER_CONFIG          Leader definition file used for overlay hints
  KEYMAP_DRAWER_VERSION  Package version to install when missing
  KEYMAP_FILE            Override the input .keymap file
  LAYOUT_FILE            Override the input layout .json file
  RAW_YAML_OUTPUT        Override the raw parsed YAML path
  BASE_YAML_OUTPUT       Override the generated base YAML path
  BASE_SVG_OUTPUT        Override the generated base SVG path
  KEYMAP_YAML_OUTPUT     Override the generated keymap YAML path
  KEYMAP_SVG_OUTPUT      Override the generated keymap SVG path
EOF
}

require_file() {
  local path=$1
  [[ -f "$path" ]] || die "Missing required file: $path"
}

require_command() {
  local cmd=$1
  command -v "$cmd" >/dev/null 2>&1 || die "Required command not found: $cmd"
}

setup_virtualenv() {
  if [[ ! -x "$VENV_DIR/bin/python" ]]; then
    log "Creating keymap-drawer virtualenv in $VENV_DIR"
    "$PYTHON_BIN" -m venv "$VENV_DIR"
  fi
}

apply_kd_patches() {
  local site_draw
  site_draw=$("$VENV_DIR/bin/python" -c "import keymap_drawer.draw; import os; print(os.path.dirname(keymap_drawer.draw.__file__))")
  local patch_dir="$SCRIPT_DIR/draw/kd_patches"
  if [[ -d "$patch_dir" ]]; then
    for f in "$patch_dir"/*.py; do
      cp "$f" "$site_draw/$(basename "$f")"
    done
    log "Applied keymap-drawer patches from $patch_dir"
  fi
}

ensure_keymap_drawer() {
  if [[ -x "$KEYMAP_BIN" ]]; then
    apply_kd_patches
    return 0
  fi

  (( SKIP_INSTALL )) && die "keymap-drawer is not installed in $VENV_DIR; rerun without --skip-install"

  log "Installing keymap-drawer==$KEYMAP_DRAWER_VERSION"
  "$VENV_DIR/bin/python" -m pip install --upgrade pip
  "$VENV_DIR/bin/python" -m pip install "keymap-drawer==$KEYMAP_DRAWER_VERSION"
  apply_kd_patches
}

SKIP_INSTALL=0
VARIANT=toucan
VARIANT_SET=0

while (($# > 0)); do
  case "$1" in
    --skip-install)
      SKIP_INSTALL=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      die "Unknown option: $1"
      ;;
    *)
      if (( VARIANT_SET )); then
        die "Only one variant may be provided"
      fi
      VARIANT=$1
      VARIANT_SET=1
      shift
      ;;
  esac
done

SCRIPT_DIR=$(
  cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
  pwd
)
REPO_ROOT=$SCRIPT_DIR

PYTHON_BIN=${PYTHON_BIN:-python3}
VENV_DIR=${VENV_DIR:-$REPO_ROOT/.keymap-drawer-venv}
DRAW_ROOT=${DRAW_ROOT:-$REPO_ROOT/draw}
DRAW_CONFIG=${DRAW_CONFIG:-$DRAW_ROOT/config.yaml}
PREPARE_SCRIPT=${PREPARE_SCRIPT:-$DRAW_ROOT/generate-keymaps.rb}
LEADER_CONFIG=${LEADER_CONFIG:-$REPO_ROOT/config/leader.dtsi}
KEYMAP_DRAWER_VERSION=${KEYMAP_DRAWER_VERSION:-0.23.0}
KEYMAP_FILE=${KEYMAP_FILE:-$REPO_ROOT/config/$VARIANT.keymap}
LAYOUT_FILE=${LAYOUT_FILE:-$REPO_ROOT/config/$VARIANT.json}
RAW_YAML_OUTPUT=${RAW_YAML_OUTPUT:-$DRAW_ROOT/$VARIANT.raw.yaml}
BASE_YAML_OUTPUT=${BASE_YAML_OUTPUT:-$DRAW_ROOT/base.yaml}
BASE_SVG_OUTPUT=${BASE_SVG_OUTPUT:-$DRAW_ROOT/base.svg}
KEYMAP_YAML_OUTPUT=${KEYMAP_YAML_OUTPUT:-$DRAW_ROOT/keymap.yaml}
KEYMAP_SVG_OUTPUT=${KEYMAP_SVG_OUTPUT:-$DRAW_ROOT/keymap.svg}
KEYMAP_BIN=$VENV_DIR/bin/keymap

require_command "$PYTHON_BIN"
require_file "$DRAW_CONFIG"
require_file "$KEYMAP_FILE"
require_file "$LAYOUT_FILE"
require_file "$LEADER_CONFIG"
require_file "$PREPARE_SCRIPT"
require_command ruby

mkdir -p "$DRAW_ROOT"

setup_virtualenv
ensure_keymap_drawer

# keymap-drawer rejects unknown top-level keys; strip the toucan: section for
# the parse step.  The draw step uses a config generated by the Ruby script
# which strips toucan: and injects leader-namespace CSS from leader_namespaces.
KD_PARSE_CONFIG=$(mktemp)
KD_DRAW_CONFIG=$(mktemp)
trap 'rm -f "$KD_PARSE_CONFIG" "$KD_DRAW_CONFIG"' EXIT
ruby -ryaml -e '
  cfg = YAML.load_file(ARGV[0])
  cfg.delete("toucan")
  puts YAML.dump(cfg)
' "$DRAW_CONFIG" > "$KD_PARSE_CONFIG"

log "Parsing $KEYMAP_FILE"
"$KEYMAP_BIN" -c "$KD_PARSE_CONFIG" parse -z "$KEYMAP_FILE" --virtual-layers Combos > "$RAW_YAML_OUTPUT"

log "Preparing draw YAML"
ruby "$PREPARE_SCRIPT" "$RAW_YAML_OUTPUT" "$BASE_YAML_OUTPUT" "$KEYMAP_YAML_OUTPUT" "$LEADER_CONFIG" "$DRAW_CONFIG" "$KD_DRAW_CONFIG"

log "Drawing $BASE_SVG_OUTPUT"
"$KEYMAP_BIN" -c "$KD_DRAW_CONFIG" draw "$BASE_YAML_OUTPUT" -j "$LAYOUT_FILE" > "$BASE_SVG_OUTPUT"

log "Drawing $KEYMAP_SVG_OUTPUT"
"$KEYMAP_BIN" -c "$KD_DRAW_CONFIG" draw "$KEYMAP_YAML_OUTPUT" -j "$LAYOUT_FILE" > "$KEYMAP_SVG_OUTPUT"

log "Wrote $RAW_YAML_OUTPUT"
log "Wrote $BASE_YAML_OUTPUT"
log "Wrote $BASE_SVG_OUTPUT"
log "Wrote $KEYMAP_YAML_OUTPUT"
log "Wrote $KEYMAP_SVG_OUTPUT"
