#pragma once

#define TOUCAN_TEXT_MODE_LINUX 0
#define TOUCAN_TEXT_MODE_MACOS 1
#define TOUCAN_TEXT_MODE_IOS 2

#define TOUCAN_TEXT_ACTION_SET_LINUX 1
#define TOUCAN_TEXT_ACTION_SET_MACOS 2
#define TOUCAN_TEXT_ACTION_SET_IOS 3
#define TOUCAN_TEXT_ACTION_CYCLE_HOST_MODE 4
#define TOUCAN_TEXT_ACTION_TOGGLE_GREEK_MODE 5

#define TOUCAN_CLIPBOARD_CUT   0
#define TOUCAN_CLIPBOARD_COPY  1
#define TOUCAN_CLIPBOARD_PASTE 2

#define TOUCAN_TEXT_SYMBOL_DE_AE 1
#define TOUCAN_TEXT_SYMBOL_DE_OE 2
#define TOUCAN_TEXT_SYMBOL_DE_UE 3
#define TOUCAN_TEXT_SYMBOL_DE_SS 4

#define TOUCAN_TEXT_SYMBOL_EL_ALPHA 10
#define TOUCAN_TEXT_SYMBOL_EL_BETA 11
#define TOUCAN_TEXT_SYMBOL_EL_GAMMA 12
#define TOUCAN_TEXT_SYMBOL_EL_DELTA 13
#define TOUCAN_TEXT_SYMBOL_EL_EPSILON 14
#define TOUCAN_TEXT_SYMBOL_EL_ZETA 15
#define TOUCAN_TEXT_SYMBOL_EL_ETA 16
#define TOUCAN_TEXT_SYMBOL_EL_THETA 17
#define TOUCAN_TEXT_SYMBOL_EL_IOTA 18
#define TOUCAN_TEXT_SYMBOL_EL_KAPPA 19
#define TOUCAN_TEXT_SYMBOL_EL_LAMBDA 20
#define TOUCAN_TEXT_SYMBOL_EL_MU 21
#define TOUCAN_TEXT_SYMBOL_EL_NU 22
#define TOUCAN_TEXT_SYMBOL_EL_XI 23
#define TOUCAN_TEXT_SYMBOL_EL_OMIKRON 24
#define TOUCAN_TEXT_SYMBOL_EL_PI 25
#define TOUCAN_TEXT_SYMBOL_EL_RHO 26
#define TOUCAN_TEXT_SYMBOL_EL_SIGMA 27
#define TOUCAN_TEXT_SYMBOL_EL_TAU 28
#define TOUCAN_TEXT_SYMBOL_EL_UPSILON 29
#define TOUCAN_TEXT_SYMBOL_EL_PHI 30
#define TOUCAN_TEXT_SYMBOL_EL_CHI 31
#define TOUCAN_TEXT_SYMBOL_EL_PSI 32
#define TOUCAN_TEXT_SYMBOL_EL_OMEGA 33
